from typing import Dict

_LIB_NAME: str = "ezpyai"

_ENV_VAR_NAME_OPENAI_API_KEY: str = "OPENAI_API_KEY"
_ENV_VAR_NAME_OPENAI_ORGANIZATION: str = "OPENAI_ORGANIZATION"
_ENV_VAR_NAME_OPENAI_PROJECT: str = "OPENAI_PROJECT"
_ENV_VAR_NAME_TEXT_GENERATION_WEBUI_API_KEY: str = "TEXT_GENERATION_WEBUI_API_KEY"
_ENV_VAR_NAME_TEXT_GENERATION_WEBUI_BASE_URL: str = "TEXT_GENERATION_WEBUI_BASE_URL"


_DICT_KEY_ID: str = "id"
_DICT_KEY_METADATA: str = "metadata"
_DICT_KEY_CONTENT: str = "content"
_DICT_KEY_SUMMARY: str = "summary"
