LIB_NAME: str = "ezpyai"

# ENVIRONMENT VARIABLES
ENV_VAR_NAME_OPENAI_API_KEY: str = "OPENAI_API_KEY"
ENV_VAR_NAME_OPENAI_ORGANIZATION: str = "OPENAI_ORGANIZATION"
ENV_VAR_NAME_OPENAI_PROJECT: str = "OPENAI_PROJECT"
ENV_VAR_NAME_TEXT_GENERATION_WEBUI_BASE_URL: str = "TEXT_GENERATION_WEBUI_BASE_URL"
ENV_VAR_NAME_TEXT_GENERATION_WEBUI_API_KEY: str = "TEXT_GENERATION_WEBUI_API_KEY"

# DICTIONARY KEYS
DICT_KEY_ID: str = "id"
DICT_KEY_METADATA: str = "metadata"
DICT_KEY_CONTENT: str = "content"
DICT_KEY_SUMMARY: str = "summary"

# HTTP METHODS
HTTP_METHOD_GET: str = "GET"
HTTP_METHOD_POST: str = "POST"

# HTTP CONTENT TYPES
HTTP_CONTENT_TYPE_JSON: str = "application/json"

# HTTP HEADERS
HTTP_HEADER_CONTENT_TYPE: str = "Content-Type"
HTTP_HEADER_AUTHORIZATION: str = "Authorization"
